In [2]:
import torch

In [8]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std = torch.tensor(1.0))
A

tensor(-0.1115)

In [9]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std = torch.arange(1, 5.0))
A

tensor([-0.1115,  0.2407, -1.1089, -0.9617])

In [10]:
torch.manual_seed(123)
A = torch.normal(mean = torch.arange(1, 5.0), std = torch.arange(1, 5.0))
A

tensor([0.8885, 2.2407, 1.8911, 3.0383])

In [12]:
torch.manual_seed(123)
B = torch.rand(3, 4)
B

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [13]:
torch.manual_seed(123)
C = torch.ones(2, 3)
D = torch.rand_like(C)
D

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [18]:
# ~N(0, 1)
torch.randn(3, 3)

tensor([[-1.7490, -0.6166, -0.2626],
        [ 0.6982, -0.3148, -1.9444],
        [ 0.9687,  0.0814,  0.3012]])

In [19]:
torch.randn_like(C)

tensor([[-0.2114,  0.3071, -0.8541],
        [ 2.6699,  0.1897, -0.3015]])

In [20]:
torch.manual_seed(123)
torch.randperm(10)

tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

In [21]:
torch.arange(start = 0, end = 10, step = 2)

tensor([0, 2, 4, 6, 8])

In [25]:
torch.linspace(start = 1, end = 10, steps = 12)

tensor([ 1.0000,  1.8182,  2.6364,  3.4545,  4.2727,  5.0909,  5.9091,  6.7273,
         7.5455,  8.3636,  9.1818, 10.0000])

In [26]:
torch.logspace(start = 0.1, end = 1.0, steps = 5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [27]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [29]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [31]:
torch.full((3, 3), fill_value = 0.25)

tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]])

In [32]:
torch.empty(3, 3)

tensor([[0.9447, 0.6217, 1.3501],
        [0.1881, 2.3891, 0.4759],
        [1.7603, 0.6547, 0.5490]])