In [59]:
import torch

In [60]:
## 比较大小

In [61]:
# 比较两个数是否接近
A = torch.tensor([10.0])
B = torch.tensor([10.1])
print(torch.allclose(A, B, rtol=1e-05, atol=1e-08,equal_nan=False))
print(torch.allclose(A, B, rtol=0.1, atol=0.01,equal_nan=False))

False
True


In [62]:
# 计算元素是否相等
A = torch.tensor([1, 2, 3, 4, 5, 6])
B = torch.arange(1, 7)
C = torch.unsqueeze(B, dim=0)
print(torch.eq(A, B))
print(torch.eq(A, C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [63]:
# 判断两个张量是否具有相同的形状和元素
print(torch.equal(A, B))
print(torch.equal(A, C))

True
False


In [64]:
# 逐元素比较是否大于等于(greater or equal)
print(torch.ge(A, B))
print(torch.ge(A, C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [65]:
# 逐元素比较是否大于(greater than)
print(torch.gt(A, B))
print(torch.gt(A, C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [66]:
# 逐元素比较是否小于等于(less or equal)
print(torch.le(A, B))
print(torch.le(A, C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [67]:
# 逐元素比较是否小于等于(less than)
print(torch.lt(A, B))
print(torch.lt(A, C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [68]:
# 逐元素比较是否不等于(not equal)
print(torch.ne(A, B))
print(torch.ne(A, C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [69]:
# 逐元素比较是否为缺失值(is nan)
A = torch.arange(1.0, 7.0)
A[2] = float("nan")
print(torch.isnan(A))

tensor([False, False,  True, False, False, False])


In [70]:
## 基本运算，逐元素运算

In [71]:
# 矩阵逐元素相乘
A = torch.arange(6.0).reshape(2, 3)
B = torch.linspace(10, 20, steps = 6).reshape(2, 3)
print(A)
print(B)
print(A * B)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,  12.,  28.],
        [ 48.,  72., 100.]])


In [72]:
# 矩阵逐元素相除
print(A / B)

tensor([[0.0000, 0.0833, 0.1429],
        [0.1875, 0.2222, 0.2500]])


In [73]:
# 矩阵逐元素相加
print(A + B)

tensor([[10., 13., 16.],
        [19., 22., 25.]])


In [74]:
# 矩阵逐元素相减
print(A - B)

tensor([[-10., -11., -12.],
        [-13., -14., -15.]])


In [75]:
# 矩阵逐元素整除
print(B / A)

tensor([[    inf, 12.0000,  7.0000],
        [ 5.3333,  4.5000,  4.0000]])


In [76]:
# 张量的幂
print(torch.pow(A, 3))
print(A ** 3)

tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])


In [77]:
# 张量的指数
torch.exp(A)

tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5981, 148.4132]])

In [78]:
# 张量的对数
torch.log(A)

tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])

In [79]:
# 张量的平方根
print(torch.sqrt(A))
print(A ** 0.5)

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])


In [80]:
# 张量的平方根倒数
print(torch.rsqrt(A))
print(1 / (A ** 0.5))

tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])
tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])


In [81]:
# 根据最大值裁剪
torch.clamp_max(A, 4)

tensor([[0., 1., 2.],
        [3., 4., 4.]])

In [82]:
# 根据最小值裁剪
torch.clamp_min(A, 3)

tensor([[3., 3., 3.],
        [3., 4., 5.]])

In [83]:
# 根据范围裁剪
torch.clamp(A, 2.5, 4)

tensor([[2.5000, 2.5000, 2.5000],
        [3.0000, 4.0000, 4.0000]])

In [84]:
## 基本运算，整个矩阵运算

In [85]:
# 矩阵的转置
C = torch.t(A)
C

tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])

In [86]:
# 矩阵运算，矩阵相乘 (A的行数要等于C的列数)
A.matmul(C)
print(A.matmul(C).eq(torch.mm(A, C)))
A = torch.arange(12.0).reshape(2, 2, 3)
A = torch.arange(12.0).reshape(2, 3, 2)
AB = torch.matmul(A, B)
AB

tensor([[True, True],
        [True, True]])


tensor([[[ 16.,  18.,  20.],
         [ 68.,  78.,  88.],
         [120., 138., 156.]],

        [[172., 198., 224.],
         [224., 258., 292.],
         [276., 318., 360.]]])

In [50]:
# 矩阵相乘只计算最后面两个维度的乘法
print(AB[0].eq(torch.matmul(A[0], B[0])))
print(AB[1].eq(torch.matmul(A[1], B[1])))

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [51]:
# 矩阵的逆
C = torch.rand(3, 3)
D = torch.inverse(C)
torch.mm(C, D)

tensor([[ 1.0000e+00, -1.4715e-07,  1.3970e-08],
        [-1.8626e-08,  1.0000e+00,  3.7253e-09],
        [ 0.0000e+00,  4.7684e-07,  1.0000e+00]])

In [88]:
# 矩阵的迹
D = torch.arange(9.0).reshape(3, 3)
print(D)
torch.trace(D)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


tensor(12.)

In [89]:
## 统计相关的计算

In [94]:
# 一维张量的最大值和最小值
A = torch.tensor([12., 34, 25, 11, 67, 32, 29, 30, 99, 55, 23, 44])
print("最大值: ", A.max())
print("最大值位置", A.argmax())
print(A[A.argmax()])
print("最小值: ", A.min())
print("最小值位置", A.argmin())
print(A[A.argmin()])

最大值:  tensor(99.)
最大值位置 tensor(8)
tensor(99.)
最小值:  tensor(11.)
最小值位置 tensor(3)
tensor(11.)


In [98]:
# 二维张量的最大值和最小值
B = A.reshape(3, 4)
print(B)
print("每行最大值: ", B.max(dim = 1))
print("每行最大值位置: ", B.argmax(dim = 1))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
每行最大值:  torch.return_types.max(
values=tensor([34., 67., 99.]),
indices=tensor([1, 0, 0]))
每行最大值位置:  tensor([1, 0, 0])


In [99]:
print("每列最小值: ", B.min(dim = 0))
print("每列最小值位置: ", B.argmin(dim = 0))

每列最小值:  torch.return_types.min(
values=tensor([12., 32., 23., 11.]),
indices=tensor([0, 1, 2, 0]))
每列最小值位置:  tensor([0, 1, 2, 0])


In [102]:
# 张量排序
torch.sort(A)

torch.return_types.sort(
values=tensor([11., 12., 23., 25., 29., 30., 32., 34., 44., 55., 67., 99.]),
indices=tensor([ 3,  0, 10,  2,  6,  7,  5,  1, 11,  9,  4,  8]))

In [104]:
# 降序
torch.sort(A, descending = True)

torch.return_types.sort(
values=tensor([99., 67., 55., 44., 34., 32., 30., 29., 25., 23., 12., 11.]),
indices=tensor([ 8,  4,  9, 11,  1,  5,  7,  6,  2, 10,  0,  3]))

In [106]:
# 对二维张量进行排序
print(B)
Bsort, Bsort_id = torch.sort(B)
print("B sort: ", Bsort)
print("B sort index: ", Bsort_id)
print("B argsort: ", torch.argsort(B))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
B sort:  tensor([[11., 12., 25., 34.],
        [29., 30., 32., 67.],
        [23., 44., 55., 99.]])
B sort index:  tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])
B argsort:  tensor([[3, 0, 2, 1],
        [2, 3, 1, 0],
        [2, 3, 1, 0]])


In [107]:
# 获取张量前几个大的数值
torch.topk(A, 4)

torch.return_types.topk(
values=tensor([99., 67., 55., 44.]),
indices=tensor([ 8,  4,  9, 11]))

In [113]:
# 获取张量前几个小的数值
torch.topk(A, 4, largest = False)

torch.return_types.topk(
values=tensor([11., 12., 23., 25.]),
indices=tensor([ 3,  0, 10,  2]))

In [114]:
# 获取二维张量每列前几个大的数值
Btop2, Btop2_id = torch.topk(B, 2, dim = 0)
print(Btop2)
print(Btop2_id)

tensor([[99., 55., 29., 44.],
        [67., 34., 25., 30.]])
tensor([[2, 2, 1, 2],
        [1, 0, 0, 1]])


In [115]:
# 获取张量第 k 小的数值和位置
torch.kthvalue(A, 3)

torch.return_types.kthvalue(
values=tensor(23.),
indices=tensor(10))

In [116]:
# 获取二维张量第 k 小的数值和位置
torch.kthvalue(B, 3, dim = 1)

torch.return_types.kthvalue(
values=tensor([25., 32., 55.]),
indices=tensor([2, 1, 1]))

In [117]:
# 获取二维张量第 k 小的数值和位置
torch.kthvalue(B, 3, dim = 1, keepdim = True)

torch.return_types.kthvalue(
values=tensor([[25.],
        [32.],
        [55.]]),
indices=tensor([[2],
        [1],
        [1]]))

In [119]:
# 计算每行平均值
print(B)
print(torch.mean(B, dim = 1, keepdim = True))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[20.5000],
        [39.5000],
        [55.2500]])


In [120]:
# 计算每列平均值
print(B)
print(torch.mean(B, dim = 0, keepdim = True))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[59.3333, 40.3333, 25.6667, 28.3333]])


In [124]:
print(B)
# 计算每行的和
print(torch.sum(B, dim = 1, keepdim = True))
# 计算每列的和
print(torch.sum(B, dim = 0, keepdim = True))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[ 82.],
        [158.],
        [221.]])
tensor([[178., 121.,  77.,  85.]])


In [125]:
print(B)
# 按行计算累加和
print(torch.cumsum(B, dim = 1))
# 按列计算累加和
print(torch.cumsum(B, dim = 0))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[ 12.,  46.,  71.,  82.],
        [ 67.,  99., 128., 158.],
        [ 99., 154., 177., 221.]])
tensor([[ 12.,  34.,  25.,  11.],
        [ 79.,  66.,  54.,  41.],
        [178., 121.,  77.,  85.]])


In [128]:
print(B)
# 计算每行的中位数
print(torch.median(B, dim = 1, keepdim = True))
# 计算每列的中位数
print(torch.median(B, dim = 0, keepdim = True))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
torch.return_types.median(
values=tensor([[12.],
        [30.],
        [44.]]),
indices=tensor([[0],
        [3],
        [3]]))
torch.return_types.median(
values=tensor([[67., 34., 25., 30.]]),
indices=tensor([[1, 0, 0, 1]]))


In [132]:
print(B)
# 按行计算乘积
print(torch.prod(B, dim = 1, keepdim = True))
# 按列计算乘积
print(torch.prod(B, dim = 0, keepdim = True))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[ 112200.],
        [1865280.],
        [5510340.]])
tensor([[79596., 59840., 16675., 14520.]])


In [133]:
print(B)
# 按行计算累乘积
print(torch.cumprod(B, dim = 1))
# 按列计算累乘积
print(torch.cumprod(B, dim = 0))

tensor([[12., 34., 25., 11.],
        [67., 32., 29., 30.],
        [99., 55., 23., 44.]])
tensor([[1.2000e+01, 4.0800e+02, 1.0200e+04, 1.1220e+05],
        [6.7000e+01, 2.1440e+03, 6.2176e+04, 1.8653e+06],
        [9.9000e+01, 5.4450e+03, 1.2524e+05, 5.5103e+06]])
tensor([[1.2000e+01, 3.4000e+01, 2.5000e+01, 1.1000e+01],
        [8.0400e+02, 1.0880e+03, 7.2500e+02, 3.3000e+02],
        [7.9596e+04, 5.9840e+04, 1.6675e+04, 1.4520e+04]])


In [134]:
# 标准差
torch.std(A)

tensor(25.0108)