In [1]:
import torch

In [41]:
A = torch.arange(12.0).reshape(3, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [42]:
torch.reshape(input = A, shape = (2, -1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [43]:
A.resize_(6, 2)

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]])

In [44]:
B = torch.arange(10.0, 19.0).reshape(3, 3)
B

tensor([[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [45]:
A.resize_as_(B)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [46]:
# dim是在指定维度处增加或减少维度
A = torch.arange(12.0).reshape(2, 6)
B = torch.unsqueeze(A, dim = 0)
print(B)
B.shape

tensor([[[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.]]])


torch.Size([1, 2, 6])

In [47]:
C = B.unsqueeze(dim = 3)
print(C)
print(C.shape)

tensor([[[[ 0.],
          [ 1.],
          [ 2.],
          [ 3.],
          [ 4.],
          [ 5.]],

         [[ 6.],
          [ 7.],
          [ 8.],
          [ 9.],
          [10.],
          [11.]]]])
torch.Size([1, 2, 6, 1])


In [48]:
# squeeze()可以移除指定的或者所有维度大小为 1 的维度
D = torch.squeeze(C)
print(D)
print(D.shape)

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])
torch.Size([2, 6])


In [49]:
E = torch.squeeze(C, dim = 0)
print(E)
print(E.shape)

tensor([[[ 0.],
         [ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.]]])
torch.Size([2, 6, 1])


In [50]:
# .expand()拓展维度
A = torch.arange(3)
B = A.expand(3, -1)
B

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [51]:
C = torch.arange(6).reshape(2, 3)
B = A.expand_as(C)
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [52]:
# .repeat()重复填充
D = B.repeat(1, 2, 2)
E = B.repeat(2, 2, 1)
print(D)
print(D.shape)
print(E)
print(E.shape)

tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])
torch.Size([1, 4, 6])
tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])
torch.Size([2, 4, 3])


In [53]:
# 切片索引获取张量元素
A = torch.arange(12).reshape(1, 3, 4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [61]:
# 获取第 0 页， 将第一维的 0 号切片取出, 未指定索引的维默认保留
A[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [66]:
# 获取第 0 行， 将第 0 页第 0 行取出
A[0, 0, :]

tensor([0, 1, 2, 3])

In [67]:
# 获取第 0 列， 将第 0 页第 0 列取出
A[0, :, 0]

tensor([0, 4, 8])

In [71]:
# 获取第 0 页， 第 1 ~ 2 列元素, 1:3 为左闭右开
A[0, :, 1:3]

tensor([[ 1,  2],
        [ 5,  6],
        [ 9, 10]])

In [74]:
# 第 0 页，第(3 - 1)行， （4 - 4）到（4 - 1）列
A[0, -1, -4:-1]

tensor([ 8,  9, 10])

In [75]:
# 条件筛选

In [77]:
B = -A
B

tensor([[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]]])

In [81]:
# 类似于三目运算符(condition)?(x):(y)
torch.where(A > 5, A, B)

tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])

In [82]:
A[A > 5]

tensor([ 6,  7,  8,  9, 10, 11])

In [83]:
# 获取张量下，上三角元素
torch.tril(A, diagonal=0,)

tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])

In [84]:
torch.triu(A, diagonal=0,)

tensor([[[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  0, 10, 11]]])

In [91]:
# 对角线元素相对偏移
torch.tril(A, diagonal=1,)

tensor([[[ 0,  1,  0,  0],
         [ 4,  5,  6,  0],
         [ 8,  9, 10, 11]]])

In [92]:
# 对角线元素相对偏移
torch.triu(A, diagonal=1,)

tensor([[[ 0,  1,  2,  3],
         [ 0,  0,  6,  7],
         [ 0,  0,  0, 11]]])

In [93]:
# 获取张量对角线元素
C = A.reshape(3, 4)
print(C)
print(torch.diag(C, diagonal=0))
print(torch.diag(C, diagonal=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  5, 10])
tensor([ 1,  6, 11])


In [94]:
# 提供对角线元素生成矩阵张量
torch.diag(torch.tensor([1, 2, 3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

In [98]:
# 拼接与拆分
A = torch.arange(6.0).reshape(2, 3)
print(A)
B = torch.linspace(0, 10, 6).reshape(2, 3)
print(B)

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [101]:
# 在第 0 维(行)连接张量
C = torch.cat((A, B), dim = 0)
C

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [102]:
# 在第 1 维(列)连接张量
C = torch.cat((A, B), dim = 1)
C

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])

In [103]:
# 在第 1 维(列)连接三个张量
C = torch.cat((A, B, A[:, 1:2]), dim = 1)
C

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.,  1.],
        [ 3.,  4.,  5.,  6.,  8., 10.,  4.]])

In [114]:
# 沿新维度连接张量，第 0 维度包含A, B两个元素，第 1 维度和第 2 维度保留了 A 和 B 的原始形状。
C = torch.stack((A, B), dim = 0)
print(C)
print(C.shape)
print(C[0])
print(C[0].equal(A))
print(C[1])
print(C[1].equal(B))

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
True
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
True


In [115]:
# 第 0 维度和第 1 维度保留了 A 和 B 的原始形状， 第 2 维度包含A, B沿该维度的值
C = torch.stack((A, B), dim = 2)
print(C)
print(C.shape)
print(C[:,:,0])
print(C[:,:,0].equal(A))
print(C[:,:,1])
print(C[:,:,1].equal(B))

tensor([[[ 0.,  0.],
         [ 1.,  2.],
         [ 2.,  4.]],

        [[ 3.,  6.],
         [ 4.,  8.],
         [ 5., 10.]]])
torch.Size([2, 3, 2])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
True
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
True


In [125]:
# 张量分割
C = torch.stack((A, B), dim = 0)
D, E = torch.chunk(C, 2, dim=0)
print(C)
print(D)
print(E)
print(C.shape)
print(D.shape)
print(E.shape)
D = torch.squeeze(D)
E = torch.squeeze(E)
print(D.shape)
print(E.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
tensor([[[0., 1., 2.],
         [3., 4., 5.]]])
tensor([[[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])
torch.Size([1, 2, 3])
torch.Size([1, 2, 3])
torch.Size([2, 3])
torch.Size([2, 3])


In [132]:
# 块数无法被指定维度的数整除时，最后一块为最小，7 / 3 = 2....1，所以最后一块为 1 列
C = torch.cat((A, B, A[:, 1:2]), dim = 1)
print(C)
D1, D2, D3 = torch.chunk(C, 3, dim = 1)
print(D1)
print(D2)
print(D3)

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.,  1.],
        [ 3.,  4.,  5.,  6.,  8., 10.,  4.]])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
tensor([[1.],
        [4.]])


In [135]:
# .split()将张量切分为块，指定每个块的大小
D1, D2, D3 = torch.split(C, [1, 2, 4], dim = 1)
print(D1)
print(D2)
print(D3)

tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.,  1.],
        [ 6.,  8., 10.,  4.]])
